name: Option Chain Telegram Alert

on:
  schedule:
    # 3:30 to 10:30 UTC corresponds to 09:00 AM to 04:00 PM IST
    - cron: '*/15 3-10 * * 1-5'
  workflow_dispatch:

jobs:
  send-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests pytz Pillow

      - name: Run alert script
        run: python alert.py
